### ISSUE TITLE
possible bower.json issue when importing to rails-assets.org

### ISSUE THREAD

**Issue by pietschy** [lumapps/lumX#144]
Hi there,

I just tried to add lumx to rails-assets.org but I'm getting the the error shown below.  

From looking at it my guess would be the `homepage` attribute is missing the http://.

Any ideas?

```
lumx#0.3.1: rake aborted!
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
ERROR:  While executing gem ... (Gem::InvalidSpecificationException)
    "ui.lumapps.com" is not a URI
/usr/local/rvm/gems/ruby-2.0.0-p598@global/gems/bundler-1.7.6/lib/bundler/gem_helper.rb:149:in `sh'
/usr/local/rvm/gems/ruby-2.0.0-p598@global/gems/bundler-1.7.6/lib/bundler/gem_helper.rb:57:in `build_gem'
/usr/local/rvm/gems/ruby-2.0.0-p598@global/gems/bundler-1.7.6/lib/bundler/gem_helper.rb:39:in `block in install'
Tasks: TOP => build
(See full trace by running task with --trace)
```

**Comment by matmkian** [comment]
I let @malexandre answer to you :-)

**Comment by malexandre** [comment]
I just push a new version of the bower.json with a valid URI. I'm not sure if it will fix this. And sorry for the delay.

**Comment by pietschy** [comment]
Hi @malexandre, thanks for that. I was able to download 0.3.32 using rails assets.
