### ISSUE TITLE
Troubled. Failed at Using LumX on VPS Sever

### ISSUE THREAD

**Issue by danielhickman** [lumapps/lumX#177]
**Intro:**
* I am trying to use LumX on a VPS server to run http://materialcolorize.com/
* I am trying to learn a tad AngularJS just enough to run either Angular Material (Doesn't look nice enough for me) or LumX
* I am familiar with HTML and CSS, but not nothing to do with SCSS or frameworks
* As I took it, LumX is supported on any webserver, but only locally works on Google's App Engine
* The following is what I did blindly, if I get this working I would gladly make additional documentation, for either here or my website. I couldn't find anything helpful anywhere, I would be glad to help you guys and other people not already familiar with frameworks.

**What I did:**
* `bower install lumx` in `/public_html/lib`
* Installed ngroute, being that is was recommended by a Angular error, in `/public_html/lib/bower_components/angular-route`
* Attempted to copy `index.html` and `app.js`
* Added the sample buttons and sample toolbar (slightly modifying it, only the text though)

**index.html:**
```html
<!DOCTYPE html>
<html>
<!-- <html ng-app="material-colorize" ng-controller="AppController" class="ng-scope"> This is from when I tried to copy the LumX demo and it's app script. I am confused, when even uploading the demo to /public_html/ doesn't work! -->
	<head>
		<title>Test LumX Document</title>
		<!-- LumX -->
		<link rel="stylesheet" href="/lib/bower_components/lumx/dist/lumx.css">
		<link rel="stylesheet" href="/lib/bower_components/mdi/materialdesignicons.css">
		<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700">
	</head>
	<body>
		<!-- Header; I swear this worked once, probably a problem with the Angular again -->
		<ng-include src="'/includes/header.html'"></ng-include>
		<!-- Body -->
		<button class="btn btn--m btn--blue btn--raised" lx-ripple>Button</button>
		<button class="btn btn--m btn--blue btn--flat" lx-ripple>Button</button>
		<button class="btn btn--m btn--blue btn--fab" lx-ripple><i class="mdi mdi-plus"></i></button>
		<button class="btn btn--m btn--blue btn--icon" lx-ripple><i class="mdi mdi-plus"></i></button>

		<!-- Angular Scripts -->
		<script src="/lib/bower_components/angular/angular.js"></script>
		<script src="/lib/bower_components/angular-route/angular-route.js"></script>

		<!-- LumX Scripts -->
		<script src="/lib/bower_components/jquery/dist/jquery.js"></script>
		<script src="/lib/bower_components/velocity/velocity.js"></script>
		<script src="/lib/bower_components/moment/min/moment-with-locales.js"></script>
		<script src="/lib/bower_components/lumx/dist/lumx.js"></script>

		<!-- Tried to copy the demo, it the dirs are outdated and is broken even if changed for me
		<script src="/lib/bower_components/lumx/modules/ripple/js/ripple_directive.js"></script>
		<script src="/lib/bower_components/lumx/modules/dropdown/js/dropdown_directive.js"></script>
		<script src="/lib/bower_components/lumx/core/js/utils/transclude_directive.js"></script>
		<script src="/lib/bower_components/lumx/core/js/utils/transclude-replace_directive.js"></script> -->

		<!-- Tried an App Script, but Angular errored out. I don't know how exactly how to use with the vague (to me) documentation.
		<script src="/app.js"></script> -->
	</body>
</html>
```

**/includes/header.html:**
```html
<!DOCTYPE html>
<!-- NavBar -->
<div class="card">
    <div class="toolbar">
        <div class="toolbar__left mr+++">
            <button class="btn btn--l btn--black btn--icon" lx-ripple>
                <i class="mdi mdi-menu"></i>
            </button>
        </div>

        <span class="toolbar__label fs-title">Material Colorize</span>

        <div class="toolbar__right">
            <lx-search-filter closed theme="light"></lx-search-filter>

            <lx-dropdown position="right" from-top>
                <button class="btn btn--l btn--black btn--icon" lx-ripple lx-dropdown-toggle>
                    <i class="mdi mdi-dots-vertical"></i>
                </button>

                <lx-dropdown-menu>
                    <ul>
                        <li><a class="dropdown-link">Settings</a>
                        </li>
                        <li class="dropdown-divider"></li>
                        <li><a class="dropdown-link dropdown-link--is-header">Meta</a>
                        </li>
                        <li><a class="dropdown-link">Help</a>
                        </li>
                        <li><a class="dropdown-link">Contact</a>
                        </li>
                    </ul>
                </lx-dropdown-menu>
            </lx-dropdown>
        </div>
    </div>
</div>
```

**/scss/styles.scss/:** (I don't think is being used)
```css
/*------------------
 Material Colorize
------------------*/

@import "settings/common";
@import "../lib/bower_components/lumx/dist/scss/lumx";
```

Any help is much appreciated. Thanks so much.

Daniel

**Comment by ThomasCrvsr** [comment]
I didn't quite get what your problem is. However, one thing I noticed in your index.html is that you import Angular before JQuery. It should be the opposite : importing JQuery before Angular.

**Comment by danielhickman** [comment]
I still can use the commented lines though
New code:
```html
<!DOCTYPE html>
<html ng-app="material-colorize" ng-controller="AppController" class="ng-scope">
	<head>
		<title>Test LumX Document</title>
		<!-- LumX -->
		<link rel="stylesheet" href="/lib/bower_components/lumx/dist/lumx.css">
		<link rel="stylesheet" href="/lib/bower_components/mdi/materialdesignicons.css">
		<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700">
	</head>
	<body>
		<!-- Header; I swear this worked once, probably a problem with the Angular again -->
		<ng-include src="'/includes/header.html'"></ng-include>
		<!-- Body -->
		<button class="btn btn--m btn--blue btn--raised" lx-ripple>Button</button>
		<button class="btn btn--m btn--blue btn--flat" lx-ripple>Button</button>
		<button class="btn btn--m btn--blue btn--fab" lx-ripple><i class="mdi mdi-plus"></i></button>
		<button class="btn btn--m btn--blue btn--icon" lx-ripple><i class="mdi mdi-plus"></i></button>

		<!-- LumX Scripts -->
		<script src="/lib/bower_components/jquery/dist/jquery.js"></script>
		<script src="/lib/bower_components/velocity/velocity.js"></script>
		<script src="/lib/bower_components/moment/min/moment-with-locales.js"></script>
		<script src="/lib/bower_components/angular/angular.js"></script>
		<script src="/lib/bower_components/angular-route/angular-route.js"></script>
		<script src="/lib/bower_components/lumx/dist/lumx.js"></script>

		<!-- Tried to copy the demo, it the dirs are outdated and is broken even if changed for me
		<script src="/lib/bower_components/lumx/modules/ripple/js/ripple_directive.js"></script>
		<script src="/lib/bower_components/lumx/modules/dropdown/js/dropdown_directive.js"></script>
		<script src="/lib/bower_components/lumx/core/js/utils/transclude_directive.js"></script>
		<script src="/lib/bower_components/lumx/core/js/utils/transclude-replace_directive.js"></script> -->

		<!-- Tried an App Script, but Angular errored out. I don't know how exactly how to use with the vague (to me) documentation. -->
		<script src="/app.js"></script>
	</body>
</html>
```

**Comment by ThomasCrvsr** [comment]
You don't need those commented lines because it is already included in /lib/bower_components/lumx/dist/lumx.js

Could you put what's in your app.js and what error message you get ?

**Comment by danielhickman** [comment]
**app.js**
```javascript
/* global angular */
/* global escape */
'use strict'; // jshint ignore:line

angular
    .module('material-colorize', [
        'ngRoute',
        'lumx',
        'hljs',
        'Services'
    ])
    .controller('AppController', function(LxNotificationService)
    {
        $scope.dropdownAlert = function()
        {
            LxNotificationService.info('Clicked!');
        };

    });
```

This is what is in it now, I tried using the demo instead and changing the index.html to match, but that didn't work either.

**Comment by ThomasCrvsr** [comment]
And what error message did you get ?

**Comment by danielhickman** [comment]
```
Uncaught SyntaxError: Unexpected token .
angular.js:4120 Uncaught Error: [$injector:modulerr] Failed to instantiate module material-colorize due to:
Error: [$injector:nomod] Module 'material-colorize' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.3.13/$injector/nomod?p0=material-colorize
    at http://materialcolorize.com/lib/bower_components/angular/angular.js:63:12
    at http://materialcolorize.com/lib/bower_components/angular/angular.js:1767:17
    at ensure (http://materialcolorize.com/lib/bower_components/angular/angular.js:1691:38)
    at module (http://materialcolorize.com/lib/bower_components/angular/angular.js:1765:14)
    at http://materialcolorize.com/lib/bower_components/angular/angular.js:4097:22
    at forEach (http://materialcolorize.com/lib/bower_components/angular/angular.js:323:20)
    at loadModules (http://materialcolorize.com/lib/bower_components/angular/angular.js:4081:5)
    at createInjector (http://materialcolorize.com/lib/bower_components/angular/angular.js:4007:11)
    at doBootstrap (http://materialcolorize.com/lib/bower_components/angular/angular.js:1445:20)
    at bootstrap (http://materialcolorize.com/lib/bower_components/angular/angular.js:1466:12)
http://errors.angularjs.org/1.3.13/$injector/modulerr?p0=material-colorize&…alcolorize.com%2Flib%2Fbower_components%2Fangular%2Fangular.js%3A1466%3A12)
```

Also the ripples and toolbars don't work. I had the toolbar appear once, but the dropdown appeared above the toolbar and didn't close at all.

**Comment by ThomasCrvsr** [comment]
And do you have any information about the syntax error you have ? A number of line or something else ?

Your main module is not included because of this syntax error.

**Comment by danielhickman** [comment]
All I did was gather the errors on materialcolorize.com in Chrome's inspector.

**Comment by danielhickman** [comment]
`Uncaught SyntaxError: Unexpected token .`  `app.js:6`

**Comment by ThomasCrvsr** [comment]
I still don't know what might be the issue causing the syntax error... One thing you forgot is to inject $scope service in your controller.

This should be :
```   
 .controller('AppController', function($scope, LxNotificationService)
    {
        $scope.dropdownAlert = function()
        {
            LxNotificationService.info('Clicked!');
        };

    });
```

But there is probably another issue coming before this...
Can you try to write this instead :
```
/* global angular */
/* global escape */
'use strict'; // jshint ignore:line

angular.module('material-colorize', [
        'ngRoute',
        'lumx',
        'hljs',
        'Services'
    ])
.controller('AppController', function($scope, LxNotificationService)
    {
        // Your controller stuff here
    });
```

**Comment by danielhickman** [comment]
```javascript
.controller('AppController', function(LxNotificationService) {
    $scope.dropdownAlert = function() {
            LxNotificationService.info('Clicked!');
    };
});
``` Is literally what's in the demo. Until the documentation and demos are correct, lol cntfigure it out ttfn bai.

**Comment by crutchcorn** [comment]
lol cntfigure it out ttfn bai

**Comment by ThomasCrvsr** [comment]
Can you precise exactly where did you take this sample ? I can't find it...

**Comment by danielhickman** [comment]
The demo's app.js

**Comment by ThomasCrvsr** [comment]
In https://github.com/lumapps/lumX/blob/master/demo/app.js, I see :
```
.controller('AppController', function($http, $scope, $location, LxNotificationService, LxDialogService, LxProgressService, Sidebar) { ... }
```
So that's not "literally" what's in the demo.
