### ISSUE TITLE
Use LumX with Ionic

### ISSUE THREAD

**Issue by ThomasCrevoisier** [lumapps/lumX#186]
Has anybody tried to use LumX with Ionic ? I'm currently rewriting a web app with LumX and I was curious about if I could use it for my cross-platform app.

**Comment by jensoleg** [comment]
Sure you can. I have removed a lot of Ionic stuff with Lumx and it works  fine. A few css classes clashes but you can get along.

**Comment by Argetloum** [comment]
Yes you can, like @jensoleg said, you must remove some Ionic stuff, or add Ionic dependencies separately ;).

**Comment by ThomasCrvsr** [comment]
Thanks :) And are the performances okay ? This is one point I'm a little afraid of actually but as I haven't tried yet, I might worry for nothing.

**Comment by Argetloum** [comment]
Performances are correct. It's not perfect, and it can't be as well as a native app of course :).

**Comment by jensoleg** [comment]
Performance depends on ...a lot of things. I have replaced UIWebView with WKWbeview resulting in HUGE performance and ressource improvements. Checkout https://github.com/Telerik-Verified-Plugins/WKWebView. WKWebview is not available for Cordova now but this plugin does the job until it is ready - on IOS.

**Comment by ThomasCrvsr** [comment]
Thanks a lot for the feedback :) I'll try it this week.

**Comment by Mavlarn** [comment]
Can anyone provide some guide to use lumx instead of ionic css?

**Comment by monkeymars** [comment]
i use lumx with ionic to get datepicker. but when i run it, following error appear on console browser
TypeError: undefined is not a function
    at Scope.e.openPicker (http://localhost:8100/lib/lumx/dist/lumx.min.js:6:3250)
    at $parseFunctionCall (http://localhost:8100/lib/ionic/js/ionic.bundle.js:20270:18)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:52468:9
    at Scope.$eval (http://localhost:8100/lib/ionic/js/ionic.bundle.js:22326:28)
    at Scope.$apply (http://localhost:8100/lib/ionic/js/ionic.bundle.js:22425:23)
    at HTMLDivElement.<anonymous> (http://localhost:8100/lib/ionic/js/ionic.bundle.js:52467:13)
    at HTMLDivElement.eventHandler (http://localhost:8100/lib/ionic/js/ionic.bundle.js:10939:21)ionic.bundle.js:19532 (anonymous function)ionic.bundle.js:16482 (anonymous function)ionic.bundle.js:22427 Scope.$applyionic.bundle.js:52467 (anonymous function)ionic.bundle.js:10939 eventHandler 

how can i fix this?

**Comment by malexandre** [comment]
We'll try to add example of usage with Ionic in the new documentation. But we do not use it a lot. Only @Argetloum used it on a project I think. 

And for @monkeymars, I'm not sure. Maybe jQuery is missing? If not, we'll need more context. If you still need help, please open a new issue.

**Comment by samuelcastro** [comment]
Can you guys, give us some sample/demo?

Thanks..
