### ISSUE TITLE
gulpfile.js errors with rubySass and lack of documentation

### ISSUE THREAD

**Issue by Sithdown** [lumapps/lumX#213]
I've installed lumX through Bower and found there wasn't any gulpfile.
Then I cloned your github repo, which has a gulpfile.
I tried it and after installing some required plugins I got stuck at this error:

```
F:\bower_components\lumx>gulp
[22:24:33] Using gulpfile F:\bower_component
s\lumx\gulpfile.js
[22:24:33] Starting 'lint'...
[22:24:34] Starting 'scss'...
[22:24:34] 'scss' errored after 120 ms
[22:24:34] TypeError: Arguments to path.join must be strings
    at f (path.js:200:13)
    at Object.filter (native)
    at Object.win32.join (path.js:205:38)
    at Object.module.exports (F:\node_module
s\gulp-ruby-sass\index.js:65:15)
    at Gulp.<anonymous> (F:\bower_components
\lumx\gulpfile.js:94:23)
    at module.exports (F:\node_modules\gulp\
node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (F:\node_m
odules\gulp\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (F:\node_m
odules\gulp\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (F:\node_modu
les\gulp\node_modules\orchestrator\index.js:134:8)
    at C:\Users\Sithdown\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129:20
[22:24:35] Finished 'lint' after 1.46 s
```

What am I doing wrong?

**Comment by ThomasCrvsr** [comment]
Why do you want a gulpfile ? By installing LumX through Bower, the lib is already packaged.

**Comment by Sithdown** [comment]
I was trying to recompile lumX after adding some modules, to no avail.

**Comment by ThomasCrvsr** [comment]
I wonder if it's not related to the new syntax to use with gulp-ruby-sass : https://github.com/sindresorhus/gulp-ruby-sass/tree/rw/1.0#usage
I encountered this problem several times.

**Comment by Sithdown** [comment]
@ThomasCrvsr That did the trick, thank you!

Old gulpfile.js:
```
gulp.task('scss', function()
{
    return gulp.src('demo/scss/lumx.scss')
        .pipe(plugins.plumber())
        .pipe(plugins.rubySass())
        .pipe(gulp.dest('build'));
});
```

New gulpfile.js:
```
gulp.task('scss', function()
{
	return plugins.rubySass('demo/scss/lumx.scss')
	.on('error', function (err) {
		console.error('Error!', err.message);
	})
	.pipe(plugins.plumber())
	.pipe(gulp.dest('build'));
})
```

Unfortunately, it seems gulp is having some problems to swallow the whole gulpfile:

```
[14:11:11] Using gulpfile F:\bower_component
s\lumx\gulpfile.js
[14:11:11] Starting 'clean:dist'...
[14:11:11] Finished 'clean:dist' after 27 ms
[14:11:11] Starting 'dist'...
[14:11:11] Starting 'scss:move-core'...
[14:11:11] Starting 'scss:move-modules'...
[14:11:11] Starting 'tpl:dropdown'...
[14:11:12] Starting 'tpl:file-input'...
[14:11:12] Starting 'tpl:text-field'...
[14:11:12] Starting 'tpl:search-filter'...
[14:11:12] Starting 'tpl:select'...
[14:11:12] Starting 'tpl:tabs'...
[14:11:12] Starting 'tpl:date-picker'...
[14:11:12] Starting 'tpl:progress'...
[14:11:12] Finished 'dist' after 223 ms
[14:11:12] Finished 'tpl:text-field' after 86 ms
[14:11:12] Finished 'tpl:date-picker' after 75 ms
[14:11:12] Finished 'tpl:progress' after 71 ms
[14:11:12] Finished 'tpl:search-filter' after 86 ms
[14:11:12] Finished 'tpl:file-input' after 95 ms
[14:11:12] Finished 'tpl:tabs' after 85 ms
[14:11:12] Finished 'tpl:dropdown' after 286 ms
[14:11:12] Finished 'tpl:select' after 92 ms
[14:11:12] Starting 'dist:scripts'...
[14:11:12] 'dist:scripts' errored after 117 ms
[14:11:12] AssertionError: missing path
    at Module.require (module.js:363:3)
    at require (module.js:384:17)
    at requireFn (F:\node_modules\gulp-load-
plugins\index.js:37:14)
    at Object.defineProperty.get (F:\node_mo
dules\gulp-load-plugins\index.js:68:18)
    at Gulp.<anonymous> (F:\bower_components
\lumx\gulpfile.js:274:22)
    at module.exports (F:\node_modules\gulp\
node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (F:\node_m
odules\gulp\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (F:\node_m
odules\gulp\node_modules\orchestrator\index.js:214:10)
    at F:\node_modules\gulp\node_modules\orc
hestrator\index.js:279:18
    at finish (F:\node_modules\gulp\node_mod
ules\orchestrator\lib\runTask.js:21:8)
[14:11:12] Finished 'scss:move-modules' after 527 ms
[14:11:12] Finished 'scss:move-core' after 541 ms
```

Offending task:
```
gulp.task('dist:scripts', ['tpl:dropdown', 'tpl:file-input', 'tpl:text-field', 'tpl:search-filter', 'tpl:select', 'tpl:tabs', 'tpl:date-picker', 'tpl:progress'], function()
{
    return gulp.src(paths.js.concat(paths.templates))
        .pipe(plugins.plumber())
        .pipe(plugins.concat('lumx.js'))
        .pipe(plugins.insert.prepend('/*\n LumX ' + options.version + '\n (c) 2014-' + new Date().getFullYear() + ' LumApps http://ui.lumapps.com\n License: MIT\n*/\n'))
        .pipe(gulp.dest('dist'))
        .pipe(plugins.uglify())
        .pipe(plugins.insert.prepend('/*\n LumX ' + options.version + '\n (c) 2014-' + new Date().getFullYear() + ' LumApps http://ui.lumapps.com\n License: MIT\n*/\n'))
        .pipe(plugins.rename('lumx.min.js'))
        .pipe(gulp.dest('dist'));
});
```

I'm using lumX as is, with its folder structure untouched, trying to re-compile both js & sass. Any ideas?

**Comment by ThomasCrvsr** [comment]
What version of Node do you use ? I don't have this problem, but I keep looking.

**Comment by Sithdown** [comment]
@ThomasCrvsr

I'm on Windows 8.1 x64

* **ruby -v**
  * ruby 2.2.1p85 (2015-02-26 revision 49769) [i386-mingw32]
* **node -v**
  * v0.12.0
* **npm -v**
  * 2.5.1
* **bower -v**
  * 1.3.12
* **gulp -v**
  * CLI version 3.8.11
  * Local version 3.8.11

**Comment by ThomasCrvsr** [comment]
Hum, it may be a problem related to Windows from the module 'gulp-load-plugins' but I didn't find a lot of things about it and I can't reproduce this problem since I'm working on MacOS.

**Comment by matmkian** [comment]
In the last version, we've reworked and fixed a lot of things. If this issue is still happening, please re-open the issue. Thank you!
