### ISSUE TITLE
TypeError: links.outerWidth is not a function ionic.bundle.js:20434

### ISSUE THREAD

**Issue by SujitDeshpande** [lumapps/lumX#316]
I get the following error while using the tabs directive with ionic framework. I cant seem to figure out what is wrong

ionic.bundle.js:20434 TypeError: links.outerWidth is not a function
    at Scope.isPaginationActive [as lxTabsIsPaginationActive] (lumx.js:2728)
    at Object.$parseFunctionCall [as get] (ionic.bundle.js:21172)
    at Scope.$get.Scope.$digest (ionic.bundle.js:23062)
    at Scope.$get.Scope.$apply (ionic.bundle.js:23333)
    at done (ionic.bundle.js:18486)
    at completeRequest (ionic.bundle.js:18676)
    at XMLHttpRequest.requestLoaded (ionic.bundle.js:18617)(anonymous function) @ ionic.bundle.js:20434$get @ ionic.bundle.js:17384$get.Scope.$digest @ ionic.bundle.js:23088$get.Scope.$apply @ ionic.bundle.js:23333done @ ionic.bundle.js:18486completeRequest @ ionic.bundle.js:18676requestLoaded @ ionic.bundle.js:18617
3ionic.bundle.js:20434 TypeError: element.parent(...).index is not a function
    at link (http://localhost:8100/lib/lumx/dist/lumx.js:3130:64)
    at invokeLinkFn (http://localhost:8100/lib/ionic/js/ionic.bundle.js:17046:9)
    at nodeLinkFn (http://localhost:8100/lib/ionic/js/ionic.bundle.js:16556:11)
    at compositeLinkFn (http://localhost:8100/lib/ionic/js/ionic.bundle.js:15905:13)
    at compositeLinkFn (http://localhost:8100/lib/ionic/js/ionic.bundle.js:15908:13)
    at publicLinkFn (http://localhost:8100/lib/ionic/js/ionic.bundle.js:15784:30)
    at $get.boundTranscludeFn (http://localhost:8100/lib/ionic/js/ionic.bundle.js:15923:16)
    at controllersBoundTransclude (http://localhost:8100/lib/ionic/js/ionic.bundle.js:16583:18)
    at ngRepeatAction (http://localhost:8100/lib/ionic/js/ionic.bundle.js:33329:15)
    at Object.$watchCollectionAction [as fn] (http://localhost:8100/lib/ionic/js/ionic.bundle.js:22935:13) <a lx-tab-link="" class="tabs-link" ng-class="{ 'tabs-link--is-active': $index === lxTabsActiveTab }" ng-click="lxTabsSetActiveTab($index)" lx-ripple="{{ lxTabsIndicator }}">(anonymous function) @ ionic.bundle.js:20434$get @ ionic.bundle.js:17384invokeLinkFn @ ionic.bundle.js:17048nodeLinkFn @ ionic.bundle.js:16556compositeLinkFn @ ionic.bundle.js:15905compositeLinkFn @ ionic.bundle.js:15908publicLinkFn @ ionic.bundle.js:15784$get.boundTranscludeFn @ ionic.bundle.js:15923controllersBoundTransclude @ ionic.bundle.js:16583ngRepeatAction @ ionic.bundle.js:33329$watchCollectionAction @ ionic.bundle.js:22935$get.Scope.$digest @ ionic.bundle.js:23070$get.Scope.$apply @ ionic.bundle.js:23333done @ ionic.bundle.js:18486completeRequest @ ionic.bundle.js:18676requestLoaded @ ionic.bundle.js:18617
ionic.bundle.js:20434 TypeError: links.outerWidth is not a function
    at Scope.isPaginationActive [as lxTabsIsPaginationActive] (lumx.js:2728)
    at $parseFunctionCall (ionic.bundle.js:21172)
    at Object.expressionInputWatch (ionic.bundle.js:21581)
    at Scope.$get.Scope.$digest (ionic.bundle.js:23062)
    at Scope.$get.Scope.$apply (ionic.bundle.js:23333)
    at done (ionic.bundle.js:18486)
    at completeRequest (ionic.bundle.js:18676)
    at XMLHttpRequest.requestLoaded (ionic.bundle.js:18617)(anonymous function) @ ionic.bundle.js:20434$get @ ionic.bundle.js:17384$get.Scope.$digest @ ionic.bundle.js:23088$get.Scope.$apply @ ionic.bundle.js:23333done @ ionic.bundle.js:18486completeRequest @ ionic.bundle.js:18676requestLoaded @ ionic.bundle.js:18617
ionic.bundle.js:20434 TypeError: links.outerWidth is not a function
    at Scope.isPaginationActive [as lxTabsIsPaginationActive] (lumx.js:2728)
    at Object.$parseFunctionCall [as get] (ionic.bundle.js:21172)
    at Scope.$get.Scope.$digest (ionic.bundle.js:23062)
    at Scope.$get.Scope.$apply (ionic.bundle.js:23333)
    at done (ionic.bundle.js:18486)
    at completeRequest (ionic.bundle.js:18676)
    at XMLHttpRequest.requestLoaded (ionic.bundle.js:18617)(anonymous function) @ ionic.bundle.js:20434$get @ ionic.bundle.js:17384$get.Scope.$digest @ ionic.bundle.js:23088$get.Scope.$apply @ ionic.bundle.js:23333done @ ionic.bundle.js:18486completeRequest @ ionic.bundle.js:18676requestLoaded @ ionic.bundle.js:18617
ionic.bundle.js:20434 TypeError: links.outerWidth is not a function
    at Scope.isPaginationActive [as lxTabsIsPaginationActive] (lumx.js:2728)
    at Array.$parseFunctionCall (ionic.bundle.js:21172)
    at $parseObjectLiteral (ionic.bundle.js:21236)
    at Scope.$get.Scope.$eval (ionic.bundle.js:23228)
    at ionic.bundle.js:29384
    at ionic.bundle.js:15625
    at forEach (ionic.bundle.js:9150)
    at Object.$get.Attributes.$set (ionic.bundle.js:15623)
    at interpolateFnWatchAction (ionic.bundle.js:16945)
    at interpolateFnWatcher (ionic.bundle.js:19004)(anonymous function) @ ionic.bundle.js:20434$get @ ionic.bundle.js:17384(anonymous function) @ ionic.bundle.js:15627forEach @ ionic.bundle.js:9150$get.Attributes.$set @ ionic.bundle.js:15623interpolateFnWatchAction @ ionic.bundle.js:16945interpolateFnWatcher @ ionic.bundle.js:19004watchGroupAction @ ionic.bundle.js:22763$get.Scope.$eval @ ionic.bundle.js:23228$get.Scope.$digest @ ionic.bundle.js:23044$get.Scope.$apply @ ionic.bundle.js:23333done @ ionic.bundle.js:18486completeRequest @ ionic.bundle.js:18676requestLoaded @ ionic.bundle.js:18617
ionic.bundle.js:20434 TypeError: links.outerWidth is not a function
    at Scope.isPaginationActive [as lxTabsIsPaginationActive] (lumx.js:2728)
    at Object.$parseFunctionCall [as get] (ionic.bundle.js:21172)
    at Scope.$get.Scope.$digest (ionic.bundle.js:23062)
    at Scope.$get.Scope.$apply (ionic.bundle.js:23333)
    at done (ionic.bundle.js:18486)
    at completeRequest (ionic.bundle.js:18676)
    at XMLHttpRequest.requestLoaded (ionic.bundle.js:18617)(anonymous function) @ ionic.bundle.js:20434$get @ ionic.bundle.js:17384$get.Scope.$digest @ ionic.bundle.js:23088$get.Scope.$apply @ ionic.bundle.js:23333done @ ionic.bundle.js:18486completeRequest @ ionic.bundle.js:18676requestLoaded @ ionic.bundle.js:18617
ionic.bundle.js:20434 TypeError: links.outerWidth is not a function
    at Scope.isPaginationActive [as lxTabsIsPaginationActive] (lumx.js:2728)
    at $parseFunctionCall (ionic.bundle.js:21172)
    at Object.expressionInputWatch (ionic.bundle.js:21581)
    at Scope.$get.Scope.$digest (ionic.bundle.js:23062)
    at Scope.$get.Scope.$apply (ionic.bundle.js:23333)
    at done (ionic.bundle.js:18486)
    at completeRequest (ionic.bundle.js:18676)
    at XMLHttpRequest.requestLoaded (ionic.bundle.js:18617)(anonymous function) @ ionic.bundle.js:20434$get @ ionic.bundle.js:17384$get.Scope.$digest @ ionic.bundle.js:23088$get.Scope.$apply @ ionic.bundle.js:23333done @ ionic.bundle.js:18486completeRequest @ ionic.bundle.js:18676requestLoaded @ ionic.bundle.js:18617
ionic.bundle.js:20434 TypeError: links.outerWidth is not a function
    at Scope.isPaginationActive [as lxTabsIsPaginationActive] (lumx.js:2728)
    at Object.$parseFunctionCall [as get] (ionic.bundle.js:21172)
    at Scope.$get.Scope.$digest (ionic.bundle.js:23062)
    at Scope.$get.Scope.$apply (ionic.bundle.js:23333)
    at done (ionic.bundle.js:18486)
    at completeRequest (ionic.bundle.js:18676)
    at XMLHttpRequest.requestLoaded (ionic.bundle.js:18617)(anonymous function) @ ionic.bundle.js:20434$get @ ionic.bundle.js:17384$get.Scope.$digest @ ionic.bundle.js:23088$get.Scope.$apply @ ionic.bundle.js:23333done @ ionic.bundle.js:18486completeRequest @ ionic.bundle.js:18676requestLoaded @ ionic.bundle.js:18617
ionic.bundle.js:20434 TypeError: links.outerWidth is not a function
    at Scope.isPaginationActive [as lxTabsIsPaginationActive] (lumx.js:2728)
    at Object.$parseFunctionCall [as get] (ionic.bundle.js:21172)
    at Scope.$get.Scope.$digest (ionic.bundle.js:23062)
    at Scope.$get.Scope.$apply (ionic.bundle.js:23333)
    at ionic.bundle.js:25059
    at completeOutstandingRequest (ionic.bundle.js:13732)
    at ionic.bundle.js:14112(anonymous function) @ ionic.bundle.js:20434$get @ ionic.bundle.js:17384$get.Scope.$digest @ ionic.bundle.js:23088$get.Scope.$apply @ ionic.bundle.js:23333(anonymous function) @ ionic.bundle.js:25059completeOutstandingRequest @ ionic.bundle.js:13732(anonymous function) @ ionic.bundle.js:14112
ionic.bundle.js:20434 TypeError: links.outerWidth is not a function
    at Scope.isPaginationActive [as lxTabsIsPaginationActive] (lumx.js:2728)
    at $parseFunctionCall (ionic.bundle.js:21172)
    at Object.expressionInputWatch (ionic.bundle.js:21581)
    at Scope.$get.Scope.$digest (ionic.bundle.js:23062)
    at Scope.$get.Scope.$apply (ionic.bundle.js:23333)
    at ionic.bundle.js:25059
    at completeOutstandingRequest (ionic.bundle.js:13732)
    at ionic.bundle.js:14112(anonymous function) @ ionic.bundle.js:20434$get @ ionic.bundle.js:17384$get.Scope.$digest @ ionic.bundle.js:23088$get.Scope.$apply @ ionic.bundle.js:23333(anonymous function) @ ionic.bundle.js:25059completeOutstandingRequest @ ionic.bundle.js:13732(anonymous function) @ ionic.bundle.js:14112
2ionic.bundle.js:20434 TypeError: links.outerWidth is not a function
    at Scope.isPaginationActive [as lxTabsIsPaginationActive] (lumx.js:2728)
    at Object.$parseFunctionCall [as get] (ionic.bundle.js:21172)
    at Scope.$get.Scope.$digest (ionic.bundle.js:23062)
    at Scope.$get.Scope.$apply (ionic.bundle.js:23333)
    at ionic.bundle.js:25059
    at completeOutstandingRequest (ionic.bundle.js:13732)
    at ionic.bundle.js:14112(anonymous function) @ ionic.bundle.js:20434$get @ ionic.bundle.js:17384$get.Scope.$digest @ ionic.bundle.js:23088$get.Scope.$apply @ ionic.bundle.js:23333(anonymous function) @ ionic.bundle.js:25059completeOutstandingRequest @ ionic.bundle.js:13732(anonymous function) @ ionic.bundle.js:14112
ionic.bundle.js:20434 TypeError: links.outerWidth is not a function
    at Scope.isPaginationActive [as lxTabsIsPaginationActive] (lumx.js:2728)
    at $parseFunctionCall (ionic.bundle.js:21172)
    at Object.expressionInputWatch (ionic.bundle.js:21581)
    at Scope.$get.Scope.$digest (ionic.bundle.js:23062)
    at Scope.$get.Scope.$apply (ionic.bundle.js:23333)
    at ionic.bundle.js:25059
    at completeOutstandingRequest (ionic.bundle.js:13732)
    at ionic.bundle.js:14112(anonymous function) @ ionic.bundle.js:20434$get @ ionic.bundle.js:17384$get.Scope.$digest @ ionic.bundle.js:23088$get.Scope.$apply @ ionic.bundle.js:23333(anonymous function) @ ionic.bundle.js:25059completeOutstandingRequest @ ionic.bundle.js:13732(anonymous function) @ ionic.bundle.js:14112
ionic.bundle.js:20434 TypeError: links.outerWidth is not a function
    at Scope.isPaginationActive [as lxTabsIsPaginationActive] (lumx.js:2728)
    at Object.$parseFunctionCall [as get] (ionic.bundle.js:21172)
    at Scope.$get.Scope.$digest (ionic.bundle.js:23062)
    at Scope.$get.Scope.$apply (ionic.bundle.js:23333)
    at ionic.bundle.js:25059
    at completeOutstandingRequest (ionic.bundle.js:13732)
    at ionic.bundle.js:14112(anonymous function) @ ionic.bundle.js:20434$get @ ionic.bundle.js:17384$get.Scope.$digest @ ionic.bundle.js:23088$get.Scope.$apply @ ionic.bundle.js:23333(anonymous function) @ ionic.bundle.js:25059completeOutstandingRequest @ ionic.bundle.js:13732(anonymous function) @ ionic.bundle.js:14112
ionic.bundle.js:20434 TypeError: links.parent(...).outerWidth is not a function
    at setIndicatorPosition (lumx.js:2916)
    at lumx.js:2679
    at ionic.bundle.js:25050
    at completeOutstandingRequest (ionic.bundle.js:13732)
    at ionic.bundle.js:14112(anonymous function) @ ionic.bundle.js:20434$get @ ionic.bundle.js:17384(anonymous function) @ ionic.bundle.js:25053completeOutstandingRequest @ ionic.bundle.js:13732(anonymous function) @ ionic.bundle.js:14112
ionic.bundle.js:20434 TypeError: links.outerWidth is not a function
    at Scope.isPaginationActive [as lxTabsIsPaginationActive] (lumx.js:2728)
    at Object.$parseFunctionCall [as get] (ionic.bundle.js:21172)
    at Scope.$get.Scope.$digest (ionic.bundle.js:23062)
    at Scope.$get.Scope.$apply (ionic.bundle.js:23333)
    at ionic.bundle.js:25059
    at completeOutstandingRequest (ionic.bundle.js:13732)
    at ionic.bundle.js:14112(anonymous function) @ ionic.bundle.js:20434$get @ ionic.bundle.js:17384$get.Scope.$digest @ ionic.bundle.js:23088$get.Scope.$apply @ ionic.bundle.js:23333(anonymous function) @ ionic.bundle.js:25059completeOutstandingRequest @ ionic.bundle.js:13732(anonymous function) @ ionic.bundle.js:14112
ionic.bundle.js:20434 TypeError: links.outerWidth is not a function
    at Scope.isPaginationActive [as lxTabsIsPaginationActive] (lumx.js:2728)
    at $parseFunctionCall (ionic.bundle.js:21172)
    at Object.expressionInputWatch (ionic.bundle.js:21581)
    at Scope.$get.Scope.$digest (ionic.bundle.js:23062)
    at Scope.$get.Scope.$apply (ionic.bundle.js:23333)
    at ionic.bundle.js:25059
    at completeOutstandingRequest (ionic.bundle.js:13732)
    at ionic.bundle.js:14112(anonymous function) @ ionic.bundle.js:20434$get @ ionic.bundle.js:17384$get.Scope.$digest @ ionic.bundle.js:23088$get.Scope.$apply @ ionic.bundle.js:23333(anonymous function) @ ionic.bundle.js:25059completeOutstandingRequest @ ionic.bundle.js:13732(anonymous function) @ ionic.bundle.js:14112
ionic.bundle.js:20434 TypeError: links.outerWidth is not a function
    at Scope.isPaginationActive [as lxTabsIsPaginationActive] (lumx.js:2728)
    at Object.$parseFunctionCall [as get] (ionic.bundle.js:21172)
    at Scope.$get.Scope.$digest (ionic.bundle.js:23062)
    at Scope.$get.Scope.$apply (ionic.bundle.js:23333)
    at ionic.bundle.js:25059
    at completeOutstandingRequest (ionic.bundle.js:13732)
    at ionic.bundle.js:14112(anonymous function) @ ionic.bundle.js:20434$get @ ionic.bundle.js:17384$get.Scope.$digest @ ionic.bundle.js:23088$get.Scope.$apply @ ionic.bundle.js:23333(anonymous function) @ ionic.bundle.js:25059completeOutstandingRequest @ ionic.bundle.js:13732(anonymous function) @ ionic.bundle.js:14112
ionic.bundle.js:20434 TypeError: links.parent(...).outerWidth is not a function
    at setIndicatorPosition (lumx.js:2916)
    at lumx.js:2679
    at ionic.bundle.js:25050
    at completeOutstandingRequest (ionic.bundle.js:13732)
    at ionic.bundle.js:14112(anonymous function) @ ionic.bundle.js:20434$get @ ionic.bundle.js:17384(anonymous function) @ ionic.bundle.js:25053completeOutstandingRequest @ ionic.bundle.js:13732(anonymous function) @ ionic.bundle.js:14112
ionic.bundle.js:20434 TypeError: links.outerWidth is not a function
    at Scope.isPaginationActive [as lxTabsIsPaginationActive] (lumx.js:2728)
    at Object.$parseFunctionCall [as get] (ionic.bundle.js:21172)
    at Scope.$get.Scope.$digest (ionic.bundle.js:23062)
    at Scope.$get.Scope.$apply (ionic.bundle.js:23333)
    at ionic.bundle.js:25059
    at completeOutstandingRequest (ionic.bundle.js:13732)
    at ionic.bundle.js:14112(anonymous function) @ ionic.bundle.js:20434$get @ ionic.bundle.js:17384$get.Scope.$digest @ ionic.bundle.js:23088$get.Scope.$apply @ ionic.bundle.js:23333(anonymous function) @ ionic.bundle.js:25059completeOutstandingRequest @ ionic.bundle.js:13732(anonymous function) @ ionic.bundle.js:14112
ionic.bundle.js:20434 TypeError: links.outerWidth is not a function
    at Scope.isPaginationActive [as lxTabsIsPaginationActive] (lumx.js:2728)
    at $parseFunctionCall (ionic.bundle.js:21172)
    at Object.expressionInputWatch (ionic.bundle.js:21581)
    at Scope.$get.Scope.$digest (ionic.bundle.js:23062)
    at Scope.$get.Scope.$apply (ionic.bundle.js:23333)
    at ionic.bundle.js:25059
    at completeOutstandingRequest (ionic.bundle.js:13732)
    at ionic.bundle.js:14112(anonymous function) @ ionic.bundle.js:20434$get @ ionic.bundle.js:17384$get.Scope.$digest @ ionic.bundle.js:23088$get.Scope.$apply @ ionic.bundle.js:23333(anonymous function) @ ionic.bundle.js:25059completeOutstandingRequest @ ionic.bundle.js:13732(anonymous function) @ ionic.bundle.js:14112
ionic.bundle.js:20434 TypeError: links.outerWidth is not a function
    at Scope.isPaginationActive [as lxTabsIsPaginationActive] (lumx.js:2728)
    at Object.$parseFunctionCall [as get] (ionic.bundle.js:21172)
    at Scope.$get.Scope.$digest (ionic.bundle.js:23062)
    at Scope.$get.Scope.$apply (ionic.bundle.js:23333)
    at ionic.bundle.js:25059
    at completeOutstandingRequest (ionic.bundle.js:13732)
    at ionic.bundle.js:14112(anonymous function) @ ionic.bundle.js:20434$get @ ionic.bundle.js:17384$get.Scope.$digest @ ionic.bundle.js:23088$get.Scope.$apply @ ionic.bundle.js:23333(anonymous function) @ ionic.bundle.js:25059completeOutstandingRequest @ ionic.bundle.js:13732(anonymous function) @ ionic.bundle.js:14112
ionic.bundle.js:20434 TypeError: links.parent(...).outerWidth is not a function
    at setIndicatorPosition (lumx.js:2916)
    at lumx.js:2679
    at ionic.bundle.js:25050
    at completeOutstandingRequest (ionic.bundle.js:13732)
    at ionic.bundle.js:14112(anonymous function) @ ionic.bundle.js:20434$get @ ionic.bundle.js:17384(anonymous function) @ ionic.bundle.js:25053completeOutstandingRequest @ ionic.bundle.js:13732(anonymous function) @ ionic.bundle.js:14112
ionic.bundle.js:20434 TypeError: links.outerWidth is not a function
    at Scope.isPaginationActive [as lxTabsIsPaginationActive] (lumx.js:2728)
    at Object.$parseFunctionCall [as get] (ionic.bundle.js:21172)
    at Scope.$get.Scope.$digest (ionic.bundle.js:23062)
    at Scope.$get.Scope.$apply (ionic.bundle.js:23333)
    at ionic.bundle.js:25059
    at completeOutstandingRequest (ionic.bundle.js:13732)
    at ionic.bundle.js:14112(anonymous function) @ ionic.bundle.js:20434$get @ ionic.bundle.js:17384$get.Scope.$digest @ ionic.bundle.js:23088$get.Scope.$apply @ ionic.bundle.js:23333(anonymous function) @ ionic.bundle.js:25059completeOutstandingRequest @ ionic.bundle.js:13732(anonymous function) @ ionic.bundle.js:14112
ionic.bundle.js:20434 TypeError: links.outerWidth is not a function
    at Scope.isPaginationActive [as lxTabsIsPaginationActive] (lumx.js:2728)
    at $parseFunctionCall (ionic.bundle.js:21172)
    at Object.expressionInputWatch (ionic.bundle.js:21581)
    at Scope.$get.Scope.$digest (ionic.bundle.js:23062)
    at Scope.$get.Scope.$apply (ionic.bundle.js:23333)
    at ionic.bundle.js:25059
    at completeOutstandingRequest (ionic.bundle.js:13732)
    at ionic.bundle.js:14112(anonymous function) @ ionic.bundle.js:20434$get @ ionic.bundle.js:17384$get.Scope.$digest @ ionic.bundle.js:23088$get.Scope.$apply @ ionic.bundle.js:23333(anonymous function) @ ionic.bundle.js:25059completeOutstandingRequest @ ionic.bundle.js:13732(anonymous function) @ ionic.bundle.js:14112
2ionic.bundle.js:20434 TypeError: links.outerWidth is not a function
    at Scope.isPaginationActive [as lxTabsIsPaginationActive] (lumx.js:2728)
    at Object.$parseFunctionCall [as get] (ionic.bundle.js:21172)
    at Scope.$get.Scope.$digest (ionic.bundle.js:23062)
    at Scope.$get.Scope.$apply (ionic.bundle.js:23333)
    at ionic.bundle.js:25059
    at completeOutstandingRequest (ionic.bundle.js:13732)
    at ionic.bundle.js:14112(anonymous function) @ ionic.bundle.js:20434$get @ ionic.bundle.js:17384$get.Scope.$digest @ ionic.bundle.js:23088$get.Scope.$apply @ ionic.bundle.js:23333(anonymous function) @ ionic.bundle.js:25059completeOutstandingRequest @ ionic.bundle.js:13732(anonymous function) @ ionic.bundle.js:14112
ionic.bundle.js:20434 TypeError: links.outerWidth is not a function
    at Scope.isPaginationActive [as lxTabsIsPaginationActive] (lumx.js:2728)
    at $parseFunctionCall (ionic.bundle.js:21172)
    at Object.expressionInputWatch (ionic.bundle.js:21581)
    at Scope.$get.Scope.$digest (ionic.bundle.js:23062)
    at Scope.$get.Scope.$apply (ionic.bundle.js:23333)
    at ionic.bundle.js:25059
    at completeOutstandingRequest (ionic.bundle.js:13732)
    at ionic.bundle.js:14112(anonymous function) @ ionic.bundle.js:20434$get @ ionic.bundle.js:17384$get.Scope.$digest @ ionic.bundle.js:23088$get.Scope.$apply @ ionic.bundle.js:23333(anonymous function) @ ionic.bundle.js:25059completeOutstandingRequest @ ionic.bundle.js:13732(anonymous function) @ ionic.bundle.js:14112
ionic.bundle.js:20434 TypeError: links.outerWidth is not a function
    at Scope.isPaginationActive [as lxTabsIsPaginationActive] (lumx.js:2728)
    at Object.$parseFunctionCall [as get] (ionic.bundle.js:21172)
    at Scope.$get.Scope.$digest (ionic.bundle.js:23062)
    at Scope.$get.Scope.$apply (ionic.bundle.js:23333)
    at ionic.bundle.js:25059
    at completeOutstandingRequest (ionic.bundle.js:13732)
    at ionic.bundle.js:14112

**Comment by SujitDeshpande** [comment]
Any update on this please?

**Comment by matmkian** [comment]
W'ere not supporting compatibility with ionic framework as there are many compatibility problems using two frameworks on a project.
