### ISSUE TITLE
Unable to load docs

### ISSUE THREAD

**Issue by prijindal** [lumapps/lumX#358]
After building the docs with gulp build and using python server or using gulp serve
but the docs can't be loaded it gives a blank screen

This is the output of devTools
```
GET http://localhost:8080/js/button/button_directive.js 
GET http://localhost:8080/js/checkbox/checkbox_directive.js 
GET http://localhost:8080/js/date-picker/date-picker_directive.js 
GET http://localhost:8080/js/dialog/dialog_directive.js 
GET http://localhost:8080/js/dropdown/dropdown_directive.js 
GET http://localhost:8080/js/fab/fab_directive.js 
GET http://localhost:8080/js/file-input/file-input_directive.js 
GET http://localhost:8080/js/notification/notification_service.js 
GET http://localhost:8080/js/progress/progress_directive.js 
GET http://localhost:8080/js/progress/progress_service.js 
GET http://localhost:8080/js/radio-button/radio-button_directive.js 
GET http://localhost:8080/js/ripple/ripple_directive.js 
GET http://localhost:8080/js/scrollbar/scrollbar_directive.js 
GET http://localhost:8080/js/search-filter/search-filter_directive.js 
GET http://localhost:8080/js/select/select_directive.js 
GET http://localhost:8080/js/switch/switch_directive.js 
GET http://localhost:8080/js/tabs/tabs_directive.js 
GET http://localhost:8080/js/text-field/text-field_directive.js 
GET http://localhost:8080/js/thumbnail/thumbnail_directive.js 
GET http://localhost:8080/js/tooltip/tooltip_directive.js 
Uncaught Error: [$injector:nomod] Module 'lumx.button' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.7/$injector/nomod?p0=lumx.button
Uncaught Error: [$injector:nomod] Module 'lumx.checkbox' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.7/$injector/nomod?p0=lumx.checkbox
Uncaught Error: [$injector:nomod] Module 'lumx.date-picker' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.7/$injector/nomod?p0=lumx.date-picker
Uncaught Error: [$injector:nomod] Module 'lumx.dropdown' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.7/$injector/nomod?p0=lumx.dropdown
Uncaught Error: [$injector:nomod] Module 'lumx.fab' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.7/$injector/nomod?p0=lumx.fab
Uncaught Error: [$injector:nomod] Module 'lumx.file-input' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.7/$injector/nomod?p0=lumx.file-input
Uncaught Error: [$injector:nomod] Module 'lumx.progress' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.7/$injector/nomod?p0=lumx.progress
Uncaught Error: [$injector:nomod] Module 'lumx.radio-button' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.7/$injector/nomod?p0=lumx.radio-button
Uncaught Error: [$injector:nomod] Module 'lumx.search-filter' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.7/$injector/nomod?p0=lumx.search-filter
Uncaught Error: [$injector:nomod] Module 'lumx.select' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.7/$injector/nomod?p0=lumx.select
Uncaught Error: [$injector:nomod] Module 'lumx.switch' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.7/$injector/nomod?p0=lumx.switch
Uncaught Error: [$injector:nomod] Module 'lumx.tabs' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.7/$injector/nomod?p0=lumx.tabs
Uncaught Error: [$injector:nomod] Module 'lumx.text-field' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.7/$injector/nomod?p0=lumx.text-field
Uncaught Error: [$injector:modulerr] Failed to instantiate module lumx-demo due to:
Error: [$injector:modulerr] Failed to instantiate module lumx due to:
Error: [$injector:modulerr] Failed to instantiate module lumx.button due to:
Error: [$injector:nomod] Module 'lumx.button' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.7/$injector/nomod?p0=lumx.button
    at REGEX_STRING_REGEXP (http://localhost:8080/libs/angular/angular.js:68:12)
    at http://localhost:8080/libs/angular/angular.js:1986:17
    at ensure (http://localhost:8080/libs/angular/angular.js:1910:38)
    at module (http://localhost:8080/libs/angular/angular.js:1984:14)
    at http://localhost:8080/libs/angular/angular.js:4390:22
    at forEach (http://localhost:8080/libs/angular/angular.js:336:20)
    at loadModules (http://localhost:8080/libs/angular/angular.js:4374:5)
    at http://localhost:8080/libs/angular/angular.js:4391:40
    at forEach (http://localhost:8080/libs/angular/angular.js:336:20)
    at loadModules (http://localhost:8080/libs/angular/angular.js:4374:5)
http://errors.angularjs.org/1.4.7/$injector/modulerr?p0=lumx.button&p1=Erro…%20(http%3A%2F%2Flocalhost%3A8080%2Flibs%2Fangular%2Fangular.js%3A4374%3A5)
    at REGEX_STRING_REGEXP (http://localhost:8080/libs/angular/angular.js:68:12)
    at http://localhost:8080/libs/angular/angular.js:4413:15
    at forEach (http://localhost:8080/libs/angular/angular.js:336:20)
    at loadModules (http://localhost:8080/libs/angular/angular.js:4374:5)
    at http://localhost:8080/libs/angular/angular.js:4391:40
    at forEach (http://localhost:8080/libs/angular/angular.js:336:20)
    at loadModules (http://localhost:8080/libs/angular/angular.js:4374:5)
    at http://localhost:8080/libs/angular/angular.js:4391:40
    at forEach (http://localhost:8080/libs/angular/angular.js:336:20)
    at loadModules (http://localhost:8080/libs/angular/angular.js:4374:5)
http://errors.angularjs.org/1.4.7/$injector/modulerr?p0=lumx&p1=Error%3A%20…%20(http%3A%2F%2Flocalhost%3A8080%2Flibs%2Fangular%2Fangular.js%3A4374%3A5)
    at REGEX_STRING_REGEXP (http://localhost:8080/libs/angular/angular.js:68:12)
    at http://localhost:8080/libs/angular/angular.js:4413:15
    at forEach (http://localhost:8080/libs/angular/angular.js:336:20)
    at loadModules (http://localhost:8080/libs/angular/angular.js:4374:5)
    at http://localhost:8080/libs/angular/angular.js:4391:40
    at forEach (http://localhost:8080/libs/angular/angular.js:336:20)
    at loadModules (http://localhost:8080/libs/angular/angular.js:4374:5)
    at createInjector (http://localhost:8080/libs/angular/angular.js:4299:11)
    at doBootstrap (http://localhost:8080/libs/angular/angular.js:1657:20)
    at bootstrap (http://localhost:8080/libs/angular/angular.js:1678:12)
http://errors.angularjs.org/1.4.7/$injector/modulerr?p0=lumx-demo&p1=Error%…20(http%3A%2F%2Flocalhost%3A8080%2Flibs%2Fangular%2Fangular.js%3A1678%3A12)
```

**Comment by matmkian** [comment]
You need to launch a simple gulp task, not gulp build
