### ISSUE TITLE
Error on removing "progress" service div on IE11

### ISSUE THREAD

**Issue by angeldaniel-adcm** [lumapps/lumX#379]
This is the error:
TypeError: Object doesn't support property or method 'remove'
 at Anonymous function (................../lumx.js:1841:17)
at Anonymous function (..................../angular.min.js:138:463)
 at e (................................................../angular.min.js:40:72)
 at Anonymous function (................../angular.min.js:44:155)

This problem only ocurr on circular progress

**Comment by matmkian** [comment]
We've just released LumX v1.0.0rc1. Progress service is no more available.
